version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/apps/front'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    open-pull-requests-limit: 2

  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    open-pull-requests-limit: 2

  - package-ecosystem: 'npm'
    directory: '/packages/types'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config-custom'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    open-pull-requests-limit: 5
